version: "3.9"

services:
  privategpt-ui:
    build:
      context: .
      dockerfile: Dockerfile.llamacpp-cpu  # or Dockerfile.ollama if you prefer
    ports:
      - "8080:80"
    environment:
      BACKEND_URL: "http://host.docker.internal:3000"
    volumes:
      - ./local_data:/app/local_data
      - ./models:/app/models
    restart: unless-stopped

